services:
  - type: web
    name: disnake_music
    env: python
    plan: free
    repo: https://github.com/andrsodremiranda/ASTM-Software.git
    buildCommand: pip3 install -r requirements.txt --no-cache-dir
    startCommand: python3 main.py
    envVars:
      - key: TOKEN
        sync: false
      - key: DEFAULT_PREFIX
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: MONGO
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.6
    autoDeploy: false # optional
